version: '3'

services:
  minio:
    image: minio/minio:RELEASE.2019-06-04T01-15-58Z
    hostname: node-1.uggla.fr
    volumes:
      - ./data1:/data1
      - ./data2:/data2
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    command: server http://node-1.uggla.fr/data1 http://node-1.uggla.fr/data2 http://node-2.uggla.fr/data1 http://node-2.uggla.fr/data2 http://node-3.uggla.fr/data1 http://node-3.uggla.fr/data2
